name: RandomTeleport
version: '${project.version}'
main: ch.ksrminecraft.randomteleport.RandomTeleport
api-version: '1.20'
commands:
  rtp:
    description: Teleportiert dich an einen Zufallsort
    aliases: [randomtp, randomteleport]
